FOOD_ALIASES = {
    "Angelica": ["angelica keiskei", "angelica herb", "wild parsnip"],
    "Savoy cabbage": ["brassica oleracea var. sabauda", "varza cretă", "varza", "crinkled cabbage"],
    "Silver linden": ["tilia argentea", "tei argintiu", "silver lime", "linden"],
    "Kiwi": ["actinidia chinensis", "kiwi fruit", "kiwifruit", "chinese gooseberry"],
    "Garden onion": ["allium cepa", "onion", "onions", "ceapă", "ceapa"],
    "Leek": ["allium porrum", "praz", "leeks"],
    "Garlic": ["allium sativum", "usturoi", "garlic cloves"],
    "Chives": ["allium schoenoprasum", "arpagic verde", "ciboulete", "chive"],
    "Lemon verbena": ["aloysia triphylla", "verbena de lămâie", "lemon beebrush", "verbena"],
    "Cashew nut": ["anacardium occidentale", "caju", "cashew", "cashews"],
    "Pineapple": ["ananas comosus", "ananas", "pineapples"],
    "Dill": ["anethum graveolens", "mărar", "dill weed"],
    "Custard apple": ["annona reticulata", "măr cremoas", "bullock's heart", "annona"],
    "Wild celery": ["apium graveolens", "ţelină", "celery", "smallage"],
    "Peanut": ["arachis hypogaea", "alune de pământ", "groundnut", "peanuts", "groundnuts"],
    "Burdock": ["arctium lappa", "brusture", "burdock root", "gobo"],
    "Horseradish": ["armoracia rusticana", "hrean", "horseradish root"],
    "Tarragon": ["artemisia dracunculus", "tărhon", "estragon", "french tarragon"],
    "Mugwort": ["artemisia vulgaris", "pelin", "common mugwort", "moxa"],
    "Asparagus": ["asparagus officinalis", "sparanghel", "asparagus spears"],
    "Oat": ["avena sativa", "ovăz", "oats", "oatmeal"],
    "Star fruit": ["averrhoa carambola", "carambola", "fructul stea", "starfruit"],
    "Brazil nut": ["bertholletia excelsa", "nucă de Brazilia", "brazil nuts", "para nut"],
    "Common beet": ["beta vulgaris", "sfeclă", "beet", "beetroot"],
    "Borage": ["borago officinalis", "borraș", "starflower", "borage herb"],
    "Chinese mustard": ["brassica juncea", "muştar chinezesc", "mustard greens", "indian mustard"],
    "Swede": ["brassica napus", "gulii", "rutabaga", "swedish turnip"],
    "Rape": ["brassica napus var. napus", "rapiţă", "rapeseed", "canola"],
    "Common cabbage": ["brassica oleracea", "varză", "cabbage", "headed cabbage"],
    "Cauliflower": ["brassica oleracea var. botrytis", "conopidă", "cauliflowers"],
    "Brussel sprouts": ["brassica oleracea var. gemmifera", "varză de bruxelles", "brussels sprouts"],
    "Kohlrabi": ["brassica oleracea var. gongylodes", "gulie", "kohlrabies"],
    "Broccoli": ["brassica oleracea var. italica", "broccoli"],
    "Chinese cabbage": ["brassica rapa", "varza chinezească", "bok choy", "napa"],
    "Turnip": ["brassica rapa var. rapa", "nap", "turnips", "white turnip"],
    "Pigeon pea": ["cajanus cajan", "mazăre porumbel", "red gram", "toor dal"],
    "Tea": ["camellia sinensis", "ceai", "tea plant", "green tea"],
    "Capers": ["capparis spinosa", "capere", "caper berries"],
    "Pepper": ["capsicum annuum", "ardei", "bell pepper", "chili pepper"],
    "Papaya": ["carica papaya", "papaia", "papaw", "pawpaw"],
    "Safflower": ["carthamus tinctorius", "sofran de America", "false saffron", "safflower oil"],
    "Caraway": ["carum carvi", "chimen", "caraway seeds"],
    "Pecan nut": ["carya illinoinensis", "pecan", "pecans", "pecan nuts"],
    "Chestnut": ["castanea", "castană", "chestnuts", "sweet chestnut"],
    "Roman camomile": ["chamaemelum nobile", "muşeţel roman", "roman chamomile", "english chamomile"],
    "Chickpea": ["cicer arietinum", "năut", "garbanzo", "chickpeas", "garbanzo bean"],
    "Endive": ["cichorium endivia", "endivă", "escarole", "curly endive"],
    "Chicory": ["cichorium intybus", "cicoare", "chicory root", "witloof"],
    "Chinese cinnamon": ["cinnamomum aromaticum", "scorţişoară chinezească", "cassia cinnamon", "cassia"],
    "Ceylon cinnamon": ["cinnamomum verum", "scorţişoară", "true cinnamon", "cinnamon sticks"],
    "Watermelon": ["citrullus lanatus", "pepene verde", "watermelons"],
    "Lime": ["citrus aurantiifolia", "limă", "key lime", "limes"],
    "Lemon": ["citrus limon", "lămâie", "lemons"],
    "Pummelo": ["citrus maxima", "pomelo", "pummelos", "shaddock"],
    "Mandarin orange (Clementine, Tangerine)": ["citrus reticulata", "mandarină", "tangerine", "clementine", "mandarin"],
    "Sweet orange": ["citrus sinensis", "portocală", "orange", "oranges"],
    "Coffee": ["coffea", "cafea", "coffee beans"],
    "Arabica coffee": ["coffea arabica", "cafea arabica", "arabica", "coffee arabica"],
    "Robusta coffee": ["coffea canephora", "cafea robusta", "robusta", "coffee robusta"],
    "Coriander": ["coriandrum sativum", "coriandru", "cilantro", "chinese parsley"],
    "Common hazelnut": ["corylus avellana", "alună", "hazelnut", "hazelnuts", "filbert"],
    "Saffron": ["crocus sativus", "şofran", "saffron threads"],
    "Muskmelon": ["cucumis melo", "pepene galben", "cantaloupe", "honeydew"],
    "Cucumber": ["cucumis sativus", "castravete", "cucumbers"],
    "Cumin": ["cuminum cyminum", "chimen roman", "cumin seeds", "comino"],
    "Turmeric": ["curcuma longa", "turmeric", "curcuma", "golden spice"],
    "Quince": ["cydonia oblonga", "gutui", "quinces"],
    "Lemon grass": ["cymbopogon citratus", "iarbă de lămâie", "lemongrass", "citronella grass"],
    "Globe artichoke": ["cynara scolymus", "anghinare", "artichoke", "artichokes"],
    "Wild carrot": ["daucus carota", "morcov sălbatic", "queen anne's lace", "wild carrot"],
    "Japanese persimmon": ["diospyros kaki", "kaki", "persimmon", "sharon fruit"],
    "Cardamom": ["elettaria cardamomum", "cardamom", "cardamon", "green cardamom"],
    "Black crowberry": ["empetrum nigrum", "merişor negru", "crowberry", "crowberries"],
    "Loquat": ["eriobotrya japonica", "nespolă", "japanese plum", "loquats"],
    "Rocket salad (ssp.)": ["eruca vesicaria ssp. sativa", "rucolă", "arugula", "rocket"],
    "Wax apple": ["eugenia javanica", "măr de ceară", "java apple", "wax jambu"],
    "Common buckwheat": ["fagopyrum esculentum", "hrişcă", "buckwheat", "kasha"],
    "Tartary buckwheat": ["fagopyrum tataricum", "hrişcă tătărească", "tartary buckwheat", "bitter buckwheat"],
    "Fig": ["ficus carica", "smochină", "figs", "common fig"],
    "Fennel": ["foeniculum vulgare", "fenicul", "fennel bulb", "fennel seeds"],
    "Strawberry": ["fragaria x ananassa", "căpşună", "strawberries"],
    "Black huckleberry": ["gaylussacia baccata", "huckleberry", "black huckleberries"],
    "Soy bean": ["glycine max", "soia", "soybeans", "soya bean", "soy"],
    "Sunflower": ["helianthus annuus", "floarea soarelui", "sunflower seeds"],
    "Sea-buckthornberry": ["hippophae rhamnoides", "cătină", "sea buckthorn", "seabuckthorn"],
    "Barley": ["hordeum vulgare", "orz", "barley grain", "malted barley"],
    "Hyssop": ["hyssopus officinalis", "isop", "hyssop herb"],
    "Star anise": ["illicium verum", "anason stelat", "star anise pods"],
    "Swamp cabbage": ["ipomoea aquatica", "spanac de apă", "water morning glory", "kangkong"],
    "Sweet potato": ["ipomoea batatas", "cartof dulce", "yam", "sweet potatoes"],
    "Black walnut": ["juglans nigra", "nuc negră", "black walnuts", "american walnut"],
    "Common walnut": ["juglans regia", "nucă", "walnuts", "english walnut"],
    "Lettuce": ["lactuca sativa", "salată verde", "salată", "lettuce leaves"],
    "Grass pea": ["lathyrus sativus", "mazăre de iarbă", "chickling vetch", "indian pea"],
    "Sweet bay": ["laurus nobilis", "dafin", "bay leaf", "bay laurel"],
    "Lentils": ["lens culinaris", "linte", "lentil", "red lentils"],
    "Garden cress": ["lepidium sativum", "creson", "cress", "peppergrass"],
    "Lovage": ["levisticum officinale", "leurdă", "lovage herb", "sea parsley"],
    "Flaxseed": ["linum usitatissimum", "in", "flax", "linseed"],
    "Mexican oregano": ["lippia graveolens", "oregano mexican", "mexican oregano herb"],
    "Lichee": ["litchi chinensis", "lici", "lychee", "litchi"],
    "Lupine": ["lupinus", "lupin", "lupins", "lupin beans"],
    "Apple": ["malus pumila", "măr", "apples", "apple fruit"],
    "Mango": ["mangifera indica", "mango", "mangoes"],
    "German camomile": ["matricaria recutita", "muşeţel german", "chamomile", "german chamomile"],
    "Lemon balm": ["melissa officinalis", "roiniţă", "melissa", "balm mint"],
    "Orange mint": ["mentha aquatica", "mentă de apă", "water mint", "bergamot mint"],
    "Cornmint": ["mentha arvensis", "mentă de câmp", "field mint", "corn mint"],
    "Spearmint": ["mentha spicata", "mentă verde", "garden mint", "spearmint leaves"],
    "Peppermint": ["mentha x piperita", "mentă piperită", "peppermint leaves", "mint"],
    "Medlar": ["mespilus germanica", "moşmon", "medlars", "common medlar"],
    "Bitter gourd": ["momordica charantia", "dovleac amar", "bitter melon", "karela"],
    "Mulberry": ["morus", "dud", "mulberries"],
    "Black mulberry": ["morus nigra", "dud negru", "black mulberries"],
    "Nutmeg": ["myristica fragrans", "nucsoara", "nucşoară", "mace"],
    "Sweet basil": ["ocimum basilicum", "busuioc", "basil", "basil leaves"],
    "Evening primrose": ["oenothera biennis", "luminita noptii", "luminiţa nopţii", "evening primrose oil"],
    "Olive": ["olea europaea", "maslină", "olives", "olive fruit"],
    "Sweet marjoram": ["origanum majorana", "maghiran", "marjoram", "knotted marjoram"],
    "Pot marjoram": ["origanum onites", "maghiran de ghiveci", "turkish oregano"],
    "Common oregano": ["origanum vulgare", "oregano", "origan", "wild marjoram"],
    "Rice": ["oryza sativa", "orez", "rice grain", "white rice"],
    "Millet": ["panicum miliaceum", "mei", "proso millet", "millets"],
    "Poppy": ["papaver", "mac", "poppy seeds", "poppies"],
    "Passion fruit": ["passiflora edulis", "fructul pasiunii", "passion fruit", "maracuja"],
    "Parsnip": ["pastinaca sativa", "păstarnac", "parsnips"],
    "Avocado": ["persea americana", "avocado", "avocados", "alligator pear"],
    "Parsley": ["petroselinum crispum", "pătrunjel", "parsley leaves", "curly parsley"],
    "Scarlet bean": ["phaseolus coccineus", "fasole roşie", "runner bean", "scarlet runner"],
    "Lima bean": ["phaseolus lunatus", "fasole lima", "butter bean", "lima beans"],
    "Common bean": ["phaseolus vulgaris", "fasole", "green bean", "kidney bean"],
    "Date": ["phoenix dactylifera", "curmale", "dates", "date fruit"],
    "Black chokeberry": ["photinia melanocarpa", "scorusar negru", "aronia", "chokeberry"],
    "Anise": ["pimpinella anisum", "anason", "aniseed", "anise seeds"],
    "Pine nut": ["pinus", "seminte de pin", "pine nuts", "pignoli"],
    "Pepper (Spice)": ["piper nigrum", "piper negru", "black pepper", "peppercorns"],
    "Pistachio": ["pistacia vera", "fistic", "pistachios", "pistachio nuts"],
    "Common pea": ["pisum sativum", "mazăre", "peas", "garden pea"],
    "Purslane": ["portulaca oleracea", "iarba grădinii", "purslane herb", "pigweed"],
    "Prunus (Cherry, Plum)": ["prunus", "cirease sau prune", "cherry", "plum"],
    "Apricot": ["prunus armeniaca", "caisă", "apricots"],
    "Sweet cherry": ["prunus avium", "cireşe", "cherries", "sweet cherries"],
    "Sour cherry": ["prunus cerasus", "vişină", "sour cherries", "morello cherry"],
    "European plum": ["prunus domestica", "prună", "plums", "prunes"],
    "Almond": ["prunus dulcis", "migdală", "almonds", "sweet almond"],
    "Peach": ["prunus persica", "piersică", "peaches"],
    "Guava": ["psidium guajava", "guava", "guavas", "common guava"],
    "Pomegranate": ["punica granatum", "rodie", "pomegranates"],
    "Pear": ["pyrus communis", "pară", "pears", "common pear"],
    "Radish": ["raphanus sativus", "ridiche", "radishes"],
    "Garden rhubarb": ["rheum rhabarbarum", "revent", "rhubarb", "rhubarb stalks"],
    "Blackcurrant": ["ribes nigrum", "coacaze negre", "coacaze", "black currant"],
    "Redcurrant": ["ribes rubrum", "coacaze rosii", "red currant", "redcurrants"],
    "Gooseberry": ["ribes uva-crispa", "agrise", "agrişe", "gooseberries"],
    "Watercress": ["rorippa nasturtium-aquaticum", "nasturtă de apă", "watercress salad"],
    "Rosemary": ["rosmarinus officinalis", "rozmarin", "rosemary herb", "rosemary leaves"],
    "Rubus (Blackberry, Raspberry)": ["rubus", "mure sau zmeura", "blackberry", "raspberry"],
    "Cloudberry": ["rubus chamaemorus", "mure arctice", "cloudberries", "bakeapple"],
    "Red raspberry": ["rubus idaeus", "zmeură", "raspberries", "red raspberries"],
    "Black raspberry": ["rubus occidentalis", "zmeură neagră", "black raspberries"],
    "Sorrel": ["rumex acetosa", "ştevia", "common sorrel", "garden sorrel"],
    "Common sage": ["salvia officinalis", "salvie", "sage", "garden sage"],
    "Black elderberry": ["sambucus nigra", "soc negru", "elderberry", "elderberries"],
    "Summer savory": ["satureja hortensis", "coada şoricelului", "savory", "summer savory herb"],
    "Winter savory": ["satureja montana", "cimbru de munte", "winter savory herb"],
    "Rye": ["secale cereale", "secară", "rye grain", "rye bread"],
    "Sesame": ["sesamum orientale", "susan", "sesame seeds", "til"],
    "Garden tomato": ["solanum lycopersicum", "rosiie", "roşie", "tomato", "tomatoes"],
    "Cherry tomato": ["solanum lycopersicum var. cerasiforme", "rosii cherry", "cherry tomatoes"],
    "Garden tomato (var.)": ["solanum lycopersicum var. lycopersicum", "roşie var.", "tomato variety"],
    "Eggplant": ["solanum melongena", "vânătă", "aubergine", "brinjal"],
    "Potato": ["solanum tuberosum", "cartof", "potatoes", "spud"],
    "Rowanberry": ["sorbus aucuparia", "scorbus", "rowan berry", "mountain ash berry"],
    "Sorghum": ["sorghum bicolor", "sorg", "sorghum grain", "milo"],
    "Spinach": ["spinacia oleracea", "spanac", "spinach leaves"],
    "Cloves": ["syzygium aromaticum", "cuisoare", "clove", "clove spice"],
    "Tamarind": ["tamarindus indica", "tamarind", "tamarind paste"],
    "Dandelion": ["taraxacum officinale", "păpădie", "dandelion greens", "dandelion leaves"],
    "Cocoa bean": ["theobroma cacao", "boabe de cacao", "cacao", "cocoa"],
    "Common thyme": ["thymus vulgaris", "cimbru", "thyme", "thyme herb"],
    "Linden": ["tilia", "tei", "linden flower", "lime tree"],
    "Small-leaf linden": ["tilia cordata", "tei cu frunze mici", "small-leaved lime"],
    "Fenugreek": ["trigonella foenum-graecum", "schinduf", "fenugreek seeds", "methi"],
    "Common wheat": ["triticum aestivum", "grâu", "wheat", "bread wheat"],
    "Vaccinium (Blueberry, Cranberry, Huckleberry)": ["vaccinium", "afine sau meriscor", "blueberry", "cranberry"],
    "Lowbush blueberry": ["vaccinium angustifolium", "afine mici", "wild blueberry", "low blueberry"],
    "Sparkleberry": ["vaccinium arboreum", "farkleberry", "tree sparkleberry"],
    "Highbush blueberry": ["vaccinium corymbosum", "afine mari", "blueberry", "highbush blueberries"],
    "American cranberry": ["vaccinium macrocarpon", "merisoare americane", "cranberry", "large cranberry"],
    "Bilberry": ["vaccinium myrtillus", "afină", "european blueberry", "bilberries"],
    "Lingonberry": ["vaccinium vitis-idaea", "merişor", "cowberry", "lingonberries"],
    "Common verbena": ["verbena officinalis", "verbena", "vervain", "common vervain"],
    "Broad bean": ["vicia faba", "bob", "fava bean", "fava beans"],
    "Adzuki bean": ["vigna angularis", "fasole adzuki", "azuki bean", "red bean"],
    "Gram bean": ["vigna mungo", "fasole gram", "black gram", "urad dal"],
    "Mung bean": ["vigna radiata", "fasole mung", "green gram", "mung beans"],
    "Climbing bean": ["vigna umbellata", "fasole căţărătoare", "rice bean", "moth bean"],
    "Cowpea": ["vigna unguiculata", "mazăre vacii", "black-eyed pea", "cowpeas"],
    "Muscadine grape": ["vitis rotundifolia", "struguri muscadini", "muscadine", "scuppernong"],
    "Common grape": ["vitis vinifera", "struguri", "grapes", "wine grape"],
    "Corn": ["zea mays", "porumb", "maize", "corn kernels"],
    "Ginger": ["zingiber officinale", "ghimbir", "ginger root", "ginger spice"],
    "Arctic blackberry": ["rubus arcticus", "mure arctice", "arctic bramble", "arctic raspberry"],
    "Banana": ["musa acuminata", "banană", "bananas"],
    "Bayberry": ["myrica", "dafin american", "bayberries", "wax myrtle"],
    "Elliott's blueberry": ["vaccinium elliottii", "elliottii blueberry", "sparkleberry"],
    "Canada blueberry": ["vaccinium myrtilloides", "afină canadiană", "canadian blueberry", "velvet-leaf blueberry"],
    "Bog bilberry": ["vaccinium uliginosum", "afin de baltă", "bog bilberry", "mossberry"],
    "Buffalo currant": ["ribes aureum var. villosum", "coacaz de bivol", "golden currant", "buffalo currant"],
    "Celeriac": ["apium graveolens var. rapaceum", "ţelină rădăcină", "celery root", "turnip-rooted celery"],
    "Celery stalks": ["apium graveolens var. dulce", "ţelină tulpină", "celery", "celery stalk"],
    "Chinese chives": ["allium tuberosum", "usturoi chinezesc", "garlic chives", "chinese garlic"],
    "European cranberry": ["vaccinium oxycoccos", "merişoare europene", "small cranberry", "marsh cranberry"],
    "Deerberry": ["vaccinium stamineum", "deerberries", "squaw huckleberry"],
    "Ginseng": ["panax", "ginseng", "ginseng root"],
    "Cascade huckleberry": ["vaccinium deliciosum", "afină cascade", "cascade blueberry"],
    "Oval-leaf huckleberry": ["vaccinium ovalifolium", "oval-leaf blueberry", "blue huckleberry"],
    "Evergreen huckleberry": ["vaccinium ovatum", "afină vesnic verde", "evergreen blueberry"],
    "Red huckleberry": ["vaccinium parvifolium", "afină roşie", "red huckleberries"],
    "Longan": ["dimocarpus longan", "longan", "longans", "dragon eye"],
    "Macadamia nut (M. tetraphylla)": ["macadamia tetraphylla", "macadamia", "rough-shelled macadamia"],
    "Garden onion (var.)": ["allium cepa var. cepa", "ceapă comună", "common onion", "onion"],
    "Summer grape": ["vitis aestivalis", "struguri de vară", "pigeon grape"],
    "Fox grape": ["vitis labrusca", "struguri fox", "fox grapes", "wild grape"],
    "Nectarine": ["prunus persica var. nucipersica", "nectarină", "nectarines", "smooth peach"],
    "Peach (var.)": ["prunus persica var. persica", "piersică var.", "peach variety"],
    "Pepper (C. baccatum)": ["capsicum baccatum var. baccatum", "ardei aji", "aji pepper", "south american pepper"],
    "Pepper (C. chinense)": ["capsicum chinense", "ardei habanero", "habanero", "scotch bonnet"],
    "Pepper (Capsicum)": ["capsicum", "ardei capsicum", "chili", "peppers"],
    "Rambutan": ["nephelium lappaceum", "rambutan", "rambutans"],
    "Red rice": ["oryza rufipogon", "orez roşu", "red rice", "wild red rice"],
    "Annual wild rice": ["zizania aquatica", "orez sălbatic anual", "water oats", "canada rice"],
    "Swiss chard": ["beta vulgaris ssp. cicla", "sfeclă elveţiană", "chard", "rainbow chard"],
    "Lemon thyme": ["thymus pulegioides", "cimbru de lămâie", "lemon thyme herb", "broad-leaved thyme"],
    "Tronchuda cabbage": ["brassica oleracea var. costata", "varza tronchuda", "portuguese cabbage", "couve"],
    "Japanese walnut": ["juglans ailanthifolia", "nucă japoneză", "heartnut", "japanese walnut"],
    "Welsh onion": ["allium fistulosum", "ceapă galleză", "bunching onion", "green onion"],
    "Hard wheat": ["triticum durum", "grâu dur", "durum wheat", "semolina wheat"],
    "Shallot": ["allium ascalonicum", "eşalotă", "shallots", "eschalot"],
    "Rocket salad": ["eruca vesicaria", "rucola", "arugula", "rocket leaves"],
    "Carrot": ["daucus carota ssp. sativus", "morcov", "carrots"],
    "Triticale": ["x triticosecale rimpaui", "triticale", "wheat-rye hybrid"],
    "Black cabbage": ["brassica oleracea var. viridis", "varza neagră", "kale", "black kale"],
    "Half-highbush blueberry": ["vaccinium angustifolium x vaccinium corymbosum", "afină hibrid", "half-high blueberry"],
    "Celery leaves": ["apium graveolens var. secalinum", "frunze de ţelină", "cutting celery", "leaf celery"],
    "Chicory leaves": ["cichorium intybus var. foliosum", "frunze de cicoare", "radicchio", "belgian endive"],
    "Komatsuna": ["brassica rapa var. perviridis", "komatsuna", "japanese mustard spinach"],
    "Pak choy": ["brassica rapa var. chinensis", "pak choi", "bok choy", "chinese white cabbage"],
    "Napa cabbage": ["brassica rapa var. pekinensis", "varza napa", "chinese cabbage", "peking cabbage"],
    "Chicory roots": ["cichorium intybus var. sativum", "rădăcină de cicoare", "chicory root", "inulin root"],
    "Grapefruit/Pummelo hybrid": ["citrus paradisi x citrus maxima", "grapefruit pomelo hibrid", "pummelo hybrid"],
    "Grapefruit": ["citrus x paradisi", "grapefruit", "grapefruits", "pomelo"],
    "Jostaberry": ["ribes × nidigrolaria", "jostaberry", "jostaberries", "gooseberry currant hybrid"],
    "Kai-lan": ["brassica oleracea var. alboglabra", "broccoli chinezesc", "chinese kale", "chinese broccoli"],
    "Italian oregano": ["origanum x majoricum", "oregano italian", "italian marjoram", "hybrid oregano"],
    "Oxheart cabbage": ["brassica oleracea var. conica", "varza oxheart", "pointy cabbage", "sweetheart cabbage"],
    "Daikon radish": ["raphanus sativus var. longipinnatus", "ridiche daikon", "japanese radish", "white radish"],
    "Black radish": ["raphanus sativus var. niger", "ridiche neagră", "black radishes", "spanish radish"],
    "Radish (var.)": ["raphanus sativus var. sativus", "ridiche var.", "common radish"],
    "Red beetroot": ["beta vulgaris var. rubra", "sfeclă roşie", "red beet", "beetroot"],
    "Sweet rowanberry": ["grataegosorbus mitschurinii", "scorbus dulce", "sweet rowan"],
    "Pineappple sage": ["salvia elegans", "salvie ananas", "pineapple sage herb"],
    "Skunk currant": ["ribes glandulosum", "coacaz puă", "skunk currant"],
    "Abalone": ["haliotis", "abalone", "sea ear", "ear shell"],
    "Abiyuch": ["crateva religiosa", "abiyuch", "spider tree fruit"],
    "Acerola": ["malpighia emarginata", "acerola", "barbados cherry", "west indian cherry"],
    "Acorn": ["quercus", "ghindă", "acorns", "oak nuts"],
    "Winter squash": ["cucurbita maxima", "dovleac de iarnă", "squash", "pumpkin"],
    "Agar": ["eucheuma", "agar", "agar-agar", "sea gelatin"],
    "Red king crab": ["paralithodes camtschaticus", "crab roşu", "king crab", "alaskan king crab"],
    "Alfalfa": ["medicago sativa", "lucernă", "alfalfa sprouts", "lucerne"],
    "Allspice": ["pimenta dioica", "ienibahar", "jamaican pepper", "pimento"],
    "Amaranth": ["amaranthus", "amarant", "amaranth greens", "pigweed"],
    "Arrowhead": ["sagittaria latifolia", "sagittaria", "wapato", "duck potato"],
    "Arrowroot": ["maranta arundinacea", "arrowroot", "arrowroot starch"],
    "Asian pear": ["pyrus pyrifolia", "păr asiatic", "nashi pear", "japanese pear"],
    "Atlantic herring": ["clupea harengus harengus", "hering atlantic", "herring", "atlantic herring fish"],
    "Atlantic mackerel": ["scomber scombrus", "macrou atlantic", "mackerel"],
    "Painted comber": ["serranus scriba", "serran", "comber fish"],
    "Atlantic pollock": ["pollachius pollachius", "pollock", "coley", "coalfish"],
    "Atlantic wolffish": ["anarhichas lupus", "pescărus de atlantic", "wolffish", "ocean catfish"],
    "Bamboo shoots": ["phyllostachys edulis", "lăstari de bambus", "bamboo", "bamboo sprouts"],
    "Striped bass": ["morone saxatilis", "biban dungat", "striped bass fish", "rockfish"],
    "Beech nut": ["fagus", "jir", "beechnuts", "beech mast"],
    "Beluga whale": ["delphinapterus leucas", "balena beluga", "beluga"],
    "Bison": ["bison bison", "bizon", "american bison", "buffalo meat"],
    "Alaska blackfish": ["dallia pectoralis", "pescăruş alaska", "alaska blackfish"],
    "Blue crab": ["callinectes sapidus", "crab albastru", "blue crabs", "chesapeake blue crab"],
    "Blue mussel": ["mytilus edulis", "midii albastre", "mussel", "mussels"],
    "Northern bluefin tuna": ["thunnus thynnus", "ton cu aripioare albastre", "bluefin tuna"],
    "Bluefish": ["pomatomus saltatrix", "bluefish", "blue fish"],
    "Wild boar": ["sus scrofa", "vier salbatic", "wild pig", "boar"],
    "Bowhead whale": ["balaena mysticetus", "balena arctiaca", "bowhead", "arctic whale"],
    "Breadfruit": ["artocarpus altilis", "fructul pâinii", "breadfruits", "jackfruit relative"],
    "Breadnut tree seed": ["brosimum alicastrum", "seminta arborelui de pâine", "ramon nut", "maya nut"],
    "Rapini": ["brassica ruvo", "rapini", "broccoli rabe", "broccoli raab"],
    "Buffalo": ["bubalus bubalis", "bivol", "water buffalo", "carabao"],
    "Burbot": ["lota lota", "mihalţ", "burbot fish", "ling cod"],
    "Giant butterbur": ["petasites japonicus", "brustur japonez", "fuki", "japanese butterbur"],
    "American butterfish": ["peprilus triacanthus", "pescăruş de unt", "butterfish"],
    "Butternut": ["juglans cinerea", "nucă unt", "white walnut", "oilnut"],
    "Butternut squash": ["cucurbita moschata", "dovleac butternut", "butternut", "butternut pumpkin"],
    "Calabash": ["lagenaria siceraria", "calabas", "bottle gourd", "white-flowered gourd"],
    "Cardoon": ["cynara cardunculus", "cardon", "thistle artichoke", "artichoke thistle"],
    "Natal plum": ["carissa macrocarpa", "prun natal", "natal plum fruit"],
    "Carob": ["ceratonia siliqua", "roşcov", "carob pods", "locust bean"],
    "Common carp": ["cyprinus carpio", "crap", "carp", "freshwater carp"],
    "Cassava": ["manihot esculenta", "manioc", "tapioca root", "yuca"],
    "Channel catfish": ["ictalurus punctatus", "somn de canal", "catfish"],
    "Chayote": ["sechium edule", "chayote", "choko", "vegetable pear"],
    "Cherimoya": ["annona cherimola", "cherimoya", "custard apple", "anon"],
    "Chervil": ["anthriscus cerefolium", "hasmujui", "haşmuţiu", "garden chervil"],
    "Chia": ["salvia hispanica", "chia", "chia seeds", "chia seed"],
    "Chicken": ["gallus gallus", "pui", "chicken meat", "poultry"],
    "Chinese broccoli": ["brassica alboglabra", "broccoli chinezesc", "chinese kale", "gai lan"],
    "Chinese chestnut": ["castanea mollissima", "castan chinezesc", "chinese chestnuts"],
    "Chinese water chestnut": ["eleocharis dulcis", "castan de apă", "water chestnut", "waterchestnut"],
    "Garland chrysanthemum": ["chrysanthemum coronarium", "crizantemă comană", "shungiku", "tong hao"],
    "Cisco": ["coregonus artedi", "cisco", "lake herring", "tullibee"],
    "Nuttall cockle": ["clinocardium nuttallii", "cocle nuttall", "cockle shellfish"],
    "Coconut": ["cocos nucifera", "cocos", "coconut", "coconut meat"],
    "Pacific cod": ["gadus macrocephalus", "cod pacific", "pacific cod fish"],
    "Atlantic cod": ["gadus morhua", "cod atlantic", "codfish", "cod"],
    "Common octopus": ["octopus vulgaris", "caracatită", "octopus"],
    "Corn salad": ["valerianella locusta", "salată de porumb", "mache", "lamb's lettuce"],
    "Cottonseed": ["gossypium", "semintă de bumbac", "cotton seed", "cottonseed oil"],
    "Catjang pea": ["vigna unguiculata ssp. cylindrica", "mazăre catjang", "catjang cowpea"],
    "Malus (Crab apple)": ["malus", "măr păduret", "crab apple", "wild apple"],
    "Squashberry": ["viburnum edule", "viburn mov", "squashberry", "lowbush cranberry"],
    "Atlantic croaker": ["micropogonias undulatus", "croaker", "atlantic croaker fish"],
    "Cusk": ["brosme brosme", "cusk", "torsk fish"],
    "Cuttlefish": ["sepiidae", "sepia", "cuttlefish squid"],
    "Mule deer": ["odocoileus", "cerb catarg", "deer", "venison"],
    "Devilfish": ["myoxocephalus", "diavol de mare", "sculpin", "bullhead"],
    "Dock": ["rumex", "ştevia", "dock leaves", "sorrel dock"],
    "Dolphin fish": ["coryphaena hippurus", "delfin peşte", "mahi-mahi", "dorado"],
    "Freshwater drum": ["aplodinotus grunniens", "tobă de apă dulce", "sheepshead", "gaspergou"],
    "Mallard duck": ["anas platyrhynchos", "rată sălbatică", "duck", "mallard"],
    "Dungeness crab": ["cancer magister", "crab dungeness", "dungeness crab"],
    "Durian": ["durio zibethinus", "durian", "king of fruits"],
    "Eastern oyster": ["crassostrea virginica", "stridie eastern", "american oyster", "oyster"],
    "Freshwater eel": ["anguilla", "anghilă de apă dulce", "eel", "river eel"],
    "Elderberry": ["sambucus", "soc", "elderberries", "elder"],
    "Elk": ["cervus canadensis", "cerb elk", "wapiti", "american elk"],
    "Emu": ["dromaius novaehollandiae", "emu", "emu meat"],
    "Oregon yampah": ["perideridia oregana", "yampah", "yampah root"],
    "European anchovy": ["engraulis encrasicolus", "hamsie", "anchovy", "anchovies"],
    "European chestnut": ["castanea sativa", "castan european", "sweet chestnut", "italian chestnut"],
    "Turbot": ["scophthalmus maximus", "turbot", "european turbot"],
    "Fireweed": ["chamerion angustifolium", "iarbaa focului", "fireweed herb", "willowherb"],
    "Florida pompano": ["trachinotus carolinus", "pompano florida", "pompano fish"],
    "Ginkgo nuts": ["ginkgo biloba", "nuci ginkgo", "ginkgo", "gingko"],
    "Greylag goose": ["anser anser", "gâscă cenusie", "greylag goose", "goose"],
    "Grape": ["vitis", "strugure", "grapes", "wine grapes"],
    "Greenland halibut/turbot": ["reinhardtius hippoglossoides", "halibut groenlandic", "greenland turbot"],
    "Groundcherry": ["physalis", "fizalis", "ground cherry", "husk tomato"],
    "Grouper": ["epinephelus", "grupere", "grouper fish"],
    "Guinea hen": ["numida meleagris", "bibilică", "guinea fowl", "guinea bird"],
    "Haddock": ["melanogrammus aeglefinus", "eglefin", "haddock fish"],
    "Hippoglossus (Common halibut)": ["hippoglossus", "halibut comun", "halibut", "common halibut"],
    "Hazelnut": ["corylus", "alună", "hazelnuts", "filbert"],
    "Hickory nut": ["carya", "nucă hickory", "hickory nuts"],
    "Horse": ["equus caballus", "cal", "horse meat", "horsemeat"],
    "Horseradish tree": ["moringa oleifera", "moringa", "drumstick tree", "ben oil tree"],
    "Alaska blueberry": ["vaccinium alaskaense", "afină alaska", "alaska blueberries"],
    "Hyacinth bean": ["lablab purpureus", "fasole lablab", "lablab bean", "egyptian bean"],
    "Irish moss": ["chondrus crispus", "muchi irlandez", "carrageen moss", "carrageenan"],
    "Pacific jack mackerel": ["trachurus symmetricus", "macrou jack", "jack mackerel"],
    "Jackfruit": ["artocarpus heterophyllus", "jaca", "jackfruit", "jack"],
    "Japanese chestnut": ["castanea crenata", "castan japonez", "japanese chestnuts"],
    "Java plum": ["syzygium cumini", "prun java", "jambolan", "indian blackberry"],
    "Jerusalem artichoke": ["helianthus tuberosus", "napă jerusalem", "sunroot", "sunchoke"],
    "Jujube": ["ziziphus zizyphus", "jujuba", "chinese date", "red date"],
    "Jute": ["corchorus olitorius", "iută", "jute leaves", "nalta jute"],
    "Kale": ["brassica napus var. pabularia", "kale", "curly kale", "borecole"],
    "Kelp": ["laminaria", "kelp", "seaweed", "sea kelp"],
    "King mackerel": ["scomberomorus cavalla", "macrou rege", "king mackerel fish", "kingfish"],
    "Kumquat": ["fortunella", "cumquat", "kumquats", "kinkan"],
    "Lambsquarters": ["chenopodium album", "loboda", "lambsquarters greens", "fat hen"],
    "Leather chiton": ["katharina tunicata", "chiton piele", "chiton shellfish"],
    "Wild leek": ["allium ampeloprasum", "praz sălbatic", "elephant garlic", "wild garlic"],
    "Common ling": ["molva molva", "ling comun", "ling fish"],
    "Lingcod": ["ophiodon elongatus", "cod ling", "lingcod fish"],
    "American lobster": ["homarus americanus", "homar american", "lobster", "lobsters"],
    "Loganberry": ["rubus loganobaccus", "loganberry", "loganberries"],
    "Lotus": ["nelumbo", "lotus", "lotus plant"],
    "Sacred lotus": ["nelumbo nucifera", "lotus sacru", "lotus root", "lotus seeds"],
    "White lupine": ["lupinus albus", "lupin alb", "white lupin", "sweet lupin"],
    "Malabar spinach": ["basella alba", "spanac malabar", "vine spinach", "ceylon spinach"],
    "Mammee apple": ["mammea americana", "măr mammee", "mammee", "tropical apricot"],
    "Purple mangosteen": ["garcinia mangostana", "mango negru", "mangosteen", "queen of fruits"],
    "Alpine sweetvetch": ["hedysarum alpinum", "hedysarum", "alpine licorice", "eskimo potato"],
    "Milkfish": ["chanos chanos", "pescăreş lapte", "milkfish", "bangus"],
    "Monkfish": ["lophius piscatorius", "pescăruş călugăr", "monkfish", "anglerfish"],
    "Moth bean": ["vigna aconitifolia", "fasole fluture", "mat bean", "turkish gram"],
    "Mountain yam": ["dioscorea pentaphylla", "igname de munte", "five-leaf yam", "mountain yam"],
    "Striped mullet": ["mugil cephalus", "chefal dungat", "striped mullet fish", "flathead mullet"],
    "White mustard": ["sinapis alba", "muştar alb", "white mustard seeds", "yellow mustard"],
    "Mustard spinach": ["brassica perviridis", "spanac muştar", "mustard greens", "tendergreen"],
    "New Zealand spinach": ["tetragonia tetragonioides", "spanac nou zeelandez", "new zealand spinach"],
    "Nopal": ["opuntia cochenillifera", "nopal", "cactus pad", "prickly pear cactus"],
    "Ocean pout": ["zoarces americanus", "ocean pout fish", "eel pout"],
    "North Pacific giant octopus": ["enteroctopus dofleini", "caracatită uriasă", "giant octopus", "pacific octopus"],
    "Ohelo berry": ["vaccinium reticulatum", "ohelo", "ohelo ai", "hawaiian cranberry"],
    "Okra": ["abelmoschus esculentus", "bamie", "okra", "ladyfinger"],
    "Tunicate": ["tunicata", "tunicat", "sea squirt", "ascidian"],
    "Ostrich": ["struthio camelus", "strut", "ostrich meat"],
    "Spotted seal": ["phoca largha", "focă pătată", "larga seal", "spotted seal"],
    "Pacific herring": ["clupea pallasii", "hering pacific", "pacific herring fish"],
    "Pacific oyster": ["crassostrea gigas", "stridie pacifică", "japanese oyster", "oysters"],
    "Pacific rockfish": ["sebastes", "rockfish pacific", "pacific rockfish", "rock cod"],
    "Velvet duck": ["melanitta fusca", "rată de catifea", "velvet scoter", "white-winged scoter"],
    "Pepper (C. frutescens)": ["capsicum annuum var. annuum", "ardei frutescens", "tabasco pepper", "cayenne"],
    "Common persimmon": ["diospyros virginiana", "kaki american", "american persimmon"],
    "Pheasant": ["phasianus colchicus", "fazan", "pheasant bird"],
    "Northern pike": ["esox lucius", "ştiucă", "pike", "freshwater pike"],
    "Pili nut": ["canarium ovatum", "nucă pili", "pili nut", "pili"],
    "Colorado pinyon": ["pinus edulis", "pin colorado", "pinyon pine", "pine nut"],
    "Pitanga": ["eugenia uniflora", "pitanga", "surinam cherry", "brazilian cherry"],
    "Plains prickly pear": ["opuntia macrorhiza", "prickly pear plains", "plains prickly pear cactus"],
    "French plantain": ["musa x paradisiaca", "banane de gătit", "plantain banana", "cooking banana"],
    "American pokeweed": ["phytolacca americana", "pokeberry", "pokeweed", "poke"],
    "Opium poppy": ["papaver somniferum", "mac opiu", "opium poppy plant", "breadseed poppy"],
    "Prairie turnip": ["pediomelum esculentum", "nap de prairie", "breadroot", "tipsin"],
    "Prickly pear": ["opuntia", "păr spinos", "cactus fruit", "tuna fruit"],
    "Quinoa": ["chenopodium quinoa", "quinoa", "quinua", "quinoa seeds"],
    "European rabbit": ["oryctolagus", "iepure european", "rabbit", "domestic rabbit"],
    "Rainbow smelt": ["osmerus mordax", "smelt arc en ciel", "smelt fish", "rainbow smelt"],
    "Rainbow trout": ["oncorhynchus mykiss", "păstrăv curcubeu", "rainbow trout fish"],
    "Malabar plum": ["syzygium jambos", "prun malabar", "rose apple", "jambos"],
    "Rose hip": ["rosa", "măceşe", "rosehips", "rose hip berry"],
    "Roselle": ["hibiscus sabdariffa", "hibiscus", "roselle flower", "jamaica sorrel"],
    "Orange roughy": ["hoplostethus atlanticus", "orange roughy", "deep sea perch"],
    "Sablefish": ["anoplopoma fimbria", "pescăruş sable", "black cod", "butterfish"],
    "Pink salmon": ["oncorhynchus gorbuscha", "somon roz", "pink salmon fish", "humpback salmon"],
    "Chum salmon": ["oncorhynchus keta", "somon chum", "chum salmon fish", "keta salmon"],
    "Coho salmon": ["oncorhynchus kisutch", "somon coho", "silver salmon"],
    "Sockeye salmon": ["oncorhynchus nerka", "somon sockeye", "red salmon", "blueback salmon"],
    "Chinook salmon": ["oncorhynchus tshawytscha", "somon chinook", "king salmon", "spring salmon"],
    "Atlantic salmon": ["salmo salar", "somon atlantic", "atlantic salmon fish", "salmon"],
    "Salmonberry": ["rubus spectabilis", "mure salmon", "salmonberry", "salmonberries"],
    "Common salsify": ["tragopogon porrifolius", "salsif", "salsify root", "oyster plant"],
    "Sapodilla": ["manilkara zapota", "sapodilla", "chiku", "naseberry"],
    "Mamey sapote": ["pouteria sapota", "mamey", "mamey sapote fruit"],
    "Spanish mackerel": ["scomberomorus maculatus", "macrou spaniol", "spanish mackerel fish"],
    "Pacific sardine": ["sardinops sagax", "sardine pacifică", "sardine", "sardines"],
    "Scallop": ["pectinidae", "scoică", "scallops", "sea scallop"],
    "Scup": ["stenotomus chrysops", "scup fish", "porgy"],
    "Sea cucumber": ["parastichopus californicus", "castravete de mare", "sea cucumber", "bêche-de-mer"],
    "Steller sea lion": ["eumetopias jubatus", "leu de mare steller", "steller sea lion"],
    "Bearded seal": ["erignathus barbatus", "focă bărboasă", "bearded seal"],
    "Ringed seal": ["pusa hispida", "focă inelară", "ringed seal", "jar seal"],
    "Sea trout": ["salmo trutta forma trutta", "păstrăv de mare", "sea trout fish", "sewin"],
    "Sesbania flower": ["sesbania bispinosa", "floare sesbania", "sesban", "sesbania"],
    "American shad": ["alosa sapidissima", "shad american", "american shad fish"],
    "Shark": ["squaliformes", "rechin", "shark meat", "shark fin"],
    "Sheefish": ["stenodus leucichthys", "sheefish", "inconnu fish"],
    "Sheep (Mutton, Lamb)": ["ovis aries", "oaie", "lamb", "mutton", "sheep meat"],
    "Sheepshead": ["archosargus probatocephalus", "sheepshead fish", "convict fish"],
    "Hedge mustard": ["sisymbrium", "muştar de gard", "hedge mustard herb"],
    "Skipjack tuna": ["katsuwonus pelamis", "ton skipjack", "skipjack", "bonito"],
    "Snapper": ["lutjanidae", "snapper peşte", "red snapper", "snapper fish"],
    "Soursop": ["annona muricata", "guanăbană", "soursop", "guanabana"],
    "Spelt": ["triticum spelta", "spălt", "spelt wheat", "dinkel wheat"],
    "Squab": ["columba", "porumbel", "squab pigeon", "pigeon meat"],
    "Strawberry guava": ["psidium cattleianum", "guava capsună", "strawberry guava", "cattley guava"],
    "Greater sturgeon": ["acipenser", "nisetru", "sturgeon", "beluga sturgeon"],
    "White sucker": ["catostomus commersonii", "sucker alb", "white sucker fish"],
    "Sugar apple": ["annona squamosa", "măr dulce", "sweetsop", "custard apple"],
    "Pumpkinseed sunfish": ["lepomis gibbosus", "pescăruş dovleac", "pumpkinseed fish"],
    "Swordfish": ["xiphias gladius", "pescăruş sabie", "swordfish", "broadbill"],
    "Taro": ["colocasia esculenta", "taro", "dasheen", "eddoe"],
    "Teff": ["eragrostis tef", "teff", "tef grain", "ethiopian grain"],
    "Tilefish": ["lopholatilus chamaeleonticeps", "tilefish", "tile fish"],
    "Mexican groundcherry": ["physalis philadelphica var. immaculata", "tomatillo", "mexican husk tomato"],
    "Towel gourd": ["luffa aegyptiaca", "luffă", "loofah", "sponge gourd"],
    "Salmonidae (Salmon, Trout)": ["salmonidae", "salmonide", "salmon family", "trout"],
    "Turkey": ["meleagris gallopavo", "curcan", "turkey meat", "turkey bird"],
    "Cattle (Beef, Veal)": ["bos taurus", "vita", "vită", "beef", "veal"],
    "Walleye": ["sander vitreus", "stiuca walleye", "walleye fish", "yellow pike"],
    "Alaska pollock": ["theragra chalcogramma", "pollock alaska", "walleye pollock"],
    "Wasabi": ["wasabia japonica", "wasabi", "japanese horseradish"],
    "Wax gourd": ["benincasa hispida", "dovleac ceara", "wax gourd", "ash gourd"],
    "Whelk": ["buccinidae", "melc de mare", "whelk shellfish"],
    "Coalfish pollock": ["pollachius virens", "pollock carbune", "coalfish", "saithe"],
    "Broad whitefish": ["coregonus nasus", "coregon nasus", "broad whitefish fish"],
    "Whitefish": ["coregonus", "coregon", "lake whitefish", "whitefish"],
    "Whiting": ["merlangius merlangus", "merlan", "whiting fish"],
    "Wild rice": ["zizania", "orez sălbatic", "wild rice grain", "water rice"],
    "Tea leaf willow": ["salix pulchra", "salcie cu frunze de ceai", "diamond willow"],
    "Winged bean": ["psophocarpus tetragonolobus", "fasole aripată", "asparagus pea", "winged beans"],
    "Yam": ["dioscorea", "igname", "yams", "tropical yam"],
    "Jicama": ["pachyrhizus erosus", "jicama", "mexican yam", "mexican turnip"],
    "Yautia": ["xanthosoma sagittifolium", "yautia", "cocoyam", "malanga"],
    "Yellowfin tuna": ["thunnus albacares", "ton cu aripioare galbene", "yellowfin", "ahi tuna"],
    "Yellowtail amberjack": ["seriola lalandi", "yellowtail", "amberjack", "yellowtail fish"],
    "Pollock": ["pollachius", "pollock", "coalfish", "alaska pollock"],
    "Albacore tuna": ["thunnus alalunga", "ton albacore", "albacore", "longfin tuna"],
    "Gadus (Common cod)": ["gadus", "cod comun", "cod", "codfish"],
    "Atlantic halibut": ["hippoglossus hippoglossus", "halibut atlantic", "atlantic halibut fish"],
    "Pacific halibut": ["hippoglossus stenolepis", "halibut pacific", "pacific halibut fish"],
    "Pacific salmon": ["oncorhynchus", "somon pacific", "pacific salmon", "salmon"],
    "Smelt": ["osmeridae", "smelt", "smelt fish", "rainbow smelt"],
    "Clupeinae (Herring, Sardine, Sprat)": ["clupeinae", "hering", "herring sardine sprat", "sardine"],
    "Spiny lobster": ["palinuridae", "homar spinos", "rock lobster", "langoustine"],
    "Snow crab": ["chionoecetes opilio", "crab de zăpadă", "snow crab", "queen crab"],
    "Black-eyed pea": ["vigna unguiculata ssp. unguiculata", "fasole cu ochi negru", "black-eyed beans", "cowpea"],
    "Deer": ["cervidae", "cerb", "venison", "deer meat"],
    "Macadamia nut": ["macadamia", "nucă macadamia", "macadamia nuts", "queensland nut"],
    "Percoidei (Bass and others)": ["percoidei", "biban", "bass", "perch family"],
    "Rabbit": ["leporidae", "iepure", "rabbit meat", "hare"],
    "Domestic goat": ["capra aegagrus hircus", "capră", "goat", "goat meat"],
    "Beefalo": ["bos taurus x bison bison", "beefalo", "cattalo", "hybrid beef"],
    "Bivalvia (Clam, Mussel, Oyster)": ["bivalvia", "bivalve", "clam mussel oyster", "shellfish"],
    "Squid": ["teuthida", "calamar", "squid", "calamari"],
    "Shrimp": ["caridea", "crevete", "shrimps", "prawns"],
    "Crayfish": ["astacidea", "rac", "crayfish", "crawfish"],
    "Flatfish": ["pleuronectiformes", "pescăreş plat", "flatfish", "flounder"],
    "Domestic pig": ["sus scrofa domestica", "porc", "pork", "pig meat"],
    "Walrus": ["odobenus rosmarus", "morsă", "walrus", "morse"],
    "Alaska wild rhubarb": ["polygonum alpinum", "revent sălbatic alaska", "alpine knotweed"],
    "Oriental wheat": ["triticum turanicum", "grâu oriental", "kamut", "khorasan wheat"],
    "Yardlong bean": ["vigna unguiculata ssp. sesquipedalis", "fasole lungă", "long bean", "snake bean"],
    "Quail": ["phasianidae", "prepeliţă", "quail bird", "quails"],
    "Boysenberry": ["rubus ursinus x idaeus", "boysenberry", "boysenberries"],
    "Persian lime": ["citrus latifolia", "limă persană", "tahiti lime", "seedless lime"],
    "Feijoa": ["feijoa sellowiana", "feijoa", "pineapple guava", "guavasteen"],
    "Rowal": ["pangium edule", "rowal", "pangium", "football fruit"],
    "Jew's ear": ["auricularia auricula-judae", "ciupercă ureche", "wood ear mushroom", "jelly ear"],
    "Common mushroom": ["agaricus bisporus", "ciupercă", "mushroom", "button mushroom"],
    "Shiitake": ["lentinus edodes", "shiitake", "chinese mushroom", "shiitake mushroom"],
    "Purple laver": ["porphyra laciniata", "alge nori", "nori", "purple laver seaweed"],
    "Wakame": ["undaria pinnatifida", "wakame", "wakame seaweed", "sea mustard"],
    "Enokitake": ["flammulina velutipes", "ciupercă enoki", "enoki", "enoki mushroom"],
    "Epazote": ["dysphania ambrosioides", "epazote", "wormseed", "mexican tea"],
    "Oyster mushroom": ["pleurotus ostreatus", "ciupercă plămân", "oyster mushrooms", "pearl oyster mushroom"],
    "Cloud ear fungus": ["auricularia polytricha", "ciupercă ureche nori", "cloud ear mushroom", "wood ear fungus"],
    "Maitake": ["grifola frondosa", "maitake", "hen of the woods", "dancing mushroom"],
    "Ostrich fern": ["matteuccia struthiopteris", "ferigă de strut", "fiddlehead fern", "fiddleheads"],
    "Spot croaker": ["leiostomus xanthurus", "spot fish", "spot croaker fish"],
    "Sourdock": ["rumex articus", "stevie arctica", "arctic dock", "sourdock herb"],
    "Tinda": ["citrullus lanatus var. fistulosus", "tinda", "indian round gourd", "tindora"],
    "Atlantic menhaden": ["brevoortia tyrannus", "menhaden atlantic", "menhaden fish", "bunker"],
    "Wheat": ["triticum", "grâu", "wheat grain", "common wheat"],
    "Common chokecherry": ["prunus virginiana", "ciresa salbatică", "chokecherry", "wild cherry"],
    "Narrowleaf cattail": ["typha angustifolia", "papură", "narrowleaf cattail plant", "bulrush"],
    "Jellyfish": ["scyphozoa", "meduza", "jellyfish", "moon jellyfish"],
    "Anchovy": ["engraulidae", "hamsie", "anchovies", "anchovy fish"],
    "Blue whiting": ["micromesistius poutassou", "merlan albastru", "blue whiting fish", "poutassou"],
    "Carp bream": ["abramis brama", "platica", "bream", "common bream"],
    "Chanterelle": ["cantharellus cibarius", "galbiori", "chanterelle mushroom", "girolle"],
    "Sturgeon": ["acipenseridae", "sturion", "sturgeon fish", "caviar fish"],
    "Charr": ["salvelinus", "caracter", "arctic char", "char fish"],
    "Cinnamon": ["cinnamomum", "scortisoara", "scorţişoară", "cinnamon spice"],
    "Crab": ["brachyura", "crab", "crabs", "sea crab"],
    "Common dab": ["limanda limanda", "calcan comun", "dab fish", "common dab fish"],
    "Spiny dogfish": ["squalus acanthias", "câine de mare", "dogfish shark", "cape shark"],
    "True frog": ["ranidae", "broască", "frog legs", "edible frog"],
    "Garfish": ["belone belone", "gar", "garfish", "needlefish"],
    "Mountain hare": ["lepus timidus", "iepure de munte", "blue hare", "variable hare"],
    "Lake trout": ["salvelinus namaycush", "păstrăv de lac", "lake trout fish", "mackinaw"],
    "Lemon sole": ["microstomus kitt", "limandă lămâie", "lemon sole fish"],
    "Clawed lobster": ["nephropidae", "homar cu clesti", "clawed lobster", "true lobster"],
    "Lumpsucker": ["cyclopteridae", "cyclopterus", "lumpfish", "lumpsucker fish"],
    "Scombridae (Bonito, Mackerel, Tuna)": ["scombridae", "scrombride", "mackerel tuna bonito", "tuna family"],
    "Marine mussel": ["mytilidae", "midii marine", "marine mussels", "mytilidae shellfish"],
    "Norway haddock": ["sebastes viviparus", "eglefin norvegian", "norway redfish"],
    "Norway lobster": ["nephrops norvegicus", "homar norvegian", "scampi", "langoustine"],
    "Norway pout": ["trisopterus esmarkii", "pout norvegian", "norway pout fish"],
    "Oil palm": ["elaeis", "palm de ulei", "palm oil", "oil palm tree"],
    "True oyster": ["ostreidae", "stridie adevarată", "true oysters", "flat oyster"],
    "Sago palm": ["metroxylon sagu", "sago", "sago palm starch"],
    "Persimmon": ["diospyros", "kaki", "persimmons", "sharon fruit"],
    "Pikeperch": ["sander lucioperca", "şalau", "pikeperch fish", "zander"],
    "Pleuronectidae (Dab, Halibut, Plaice)": ["pleuronectidae", "calcan", "dab halibut plaice", "flatfish family"],
    "Rock ptarmigan": ["lagopus muta", "cocoras de stncă", "ptarmigan", "rock ptarmigan bird"],
    "Pacific ocean perch": ["sebastes alutus", "biban de pacific", "pacific ocean perch fish"],
    "Black salsify": ["scorzonera hispanica", "scorzonera", "black salsify root", "viper grass"],
    "True seal": ["phocidae", "foca", "seal", "true seals"],
    "Red algae": ["rhodophyta", "alge rosii", "red algae seaweed", "rhodophyta algae"],
    "Kombu": ["saccharina japonica", "kombu", "kombu seaweed", "kelp nori"],
    "Snail": ["gastropoda", "melc", "snail escargot", "escargot"],
    "True sole": ["soleidae", "talpa de mare", "sole fish", "dover sole"],
    "Catfish": ["siluriformes", "somn", "catfish", "channel catfish"],
    "Thistle": ["cirsium", "ciulin", "thistle plant", "milk thistle"],
    "Walnut": ["juglans", "nucă", "walnuts", "walnut nut"],
    "Cetacea (Dolphin, Porpoise, Whale)": ["cetacea", "cetacee", "dolphin porpoise whale", "whale"],
    "Columbidae (Dove, Pigeon)": ["columbidae", "porumbel", "dove pigeon", "pigeon"],
    "Conch": ["strombidae", "conch scoică", "conch shell", "queen conch"],
    "Cichlidae (Tilapia)": ["cichlidae", "tilapia", "cichlid fish", "nile tilapia"],
    "Green turtle": ["chelonia mydas", "brostace verde", "green sea turtle"],
    "Hibiscus tea": ["hibiscus sabbariffa", "ceai de hibiscus", "hibiscus", "roselle tea"],
    "Morchella (Morel)": ["morchellaceae", "zbarcită", "morel mushroom", "morels"],
    "Horned melon": ["cucumis metuliferus", "pepene cu coarne", "kiwano", "african horned cucumber"],
    "Babassu palm": ["attalea speciosa", "palm babassu", "babassu oil", "babassu"],
    "Cupuaçu": ["theobroma grandiflorum", "cupuacu", "cupuassu", "tropical chocolate"],
    "Shea tree": ["vitellaria paradoxa", "shea", "shea butter tree", "karite"],
    "Oil-seed Camellia": ["camellia oleifera", "camelia ulei", "tea oil plant", "camellia oil"],
    "Ucuhuba": ["virola surinamensis", "ucuhuba", "virola nut", "cumala"],
    "Nance": ["byrsonima crassifolia", "nance", "nance fruit", "golden spoon"],
    "Naranjilla": ["solanum quitoense", "naranjilla", "lulo", "little orange"],
    "Tree fern": ["cyathea", "ferigă arborescentă", "tree fern plant"],
    "Greenthread tea": ["thelesperma", "greenthread tea plant", "navajo tea"],
    "Ascidians": ["ascidiacea", "ascidie", "sea squirt", "tunicate"],
    "Yellow pond-lily": ["nuphar lutea", "lilţi galben de helessteu", "yellow pond lily", "spatterdock"],
    "Pepper (C. pubescens)": ["capsicum pubescens", "ardei pubescens", "rocoto pepper", "locoto"],
    "Soft-necked garlic": ["allium sativum l. var. sativum", "usturoi cu gat moale", "softneck garlic"],
    "Cabbage": ["brassica oleracea var. capitata", "varza", "cabbage head", "headed cabbage"],
    "Chinese bayberry": ["myrica rubra", "bayberry chinezesc", "chinese strawberry tree", "yang mei"],
    "Sunburst squash (pattypan squash)": ["cucurbita pepo var. clypeata", "dovleac patisson", "pattypan squash", "pattypan"],
    "Green zucchini": ["cucurbita pepo var. cylindrica", "dovlecel verde", "zucchini", "courgette"],
    "Yellow zucchini": ["cucurbita pepo var. cylindrica", "dovlecel galben", "yellow courgette", "yellow squash"],
    "Green bell pepper": ["capsicum annuum", "ardei verde", "green pepper", "bell pepper"],
    "Yellow bell pepper": ["capsicum annuum", "ardei galben", "yellow pepper"],
    "Orange bell pepper": ["capsicum annuum", "ardei portocaliu", "orange pepper"],
    "Red bell pepper": ["capsicum annuum", "ardei roşu", "red pepper", "pimento"],
    "Italian sweet red pepper": ["capsicum annuum", "ardei italiano dulce", "sweet red pepper"],
    "Yellow wax bean": ["phaseolus vulgaris", "fasole galbenă", "wax bean", "butter bean"],
    "Green bean": ["phaseolus vulgaris", "fasole verde", "green beans", "string bean"],
    "Saskatoon berry": ["amelanchier alnifolia", "saskatoon", "serviceberry", "juneberry"],
    "Nanking cherry": ["prunus tomentosa", "cires nanking", "nanking cherry", "manchu cherry"],
    "Japanese pumpkin": ["cucurbita maxima", "dovleac japonez", "kabocha", "japanese squash"],
    "White cabbage": ["brassica oleracea l. var. capitata l. f. alba dc.", "varza alba", "white headed cabbage"],
    "Romaine lettuce": ["lactuca sativa l. var. longifolia", "salata romana", "cos lettuce", "romaine"],
    "Mundu": ["garcinia dulcis", "mundu", "mundu fruit"],
    "Rabbiteye blueberry": ["vaccinium virgatum", "afina rabbiteye", "rabbiteye blueberry"],
    "Yali pear": ["pyrus x bretschneideri", "par yali", "yali pear", "nashi pear"],
    "Evergreen blackberry": ["rubus laciniatus", "mura vesnica verde", "cutleaf blackberry"],
    "Asparagus fern": ["asparagus setaceus", "feriga sparanghel", "asparagus fern"],
    "Thornless blackberry": ["rubus ulmifolius", "mura fara spini", "thornless blackberry"],
    "Tropical highland blackberry": ["rubus adenotrichos", "mura tropicala montana", "highland blackberry"],
    "Andean blackberry": ["rubus glaucus", "mura andina", "mora de castilla", "andean blackberry"],
    "Blackberry": ["rubus", "mure", "blackberries", "wild blackberry"],
    "Guarana": ["paullinia cupana", "guarana", "guarana seeds", "brazilian cocoa"],
    "Mate": ["ilex paraguariensis", "mate", "yerba mate", "yerba"],
    "Sour orange": ["citrus x aurantium", "portocala acra", "bitter orange", "seville orange"],
    "White mulberry": ["morus alba", "dud alb", "white mulberry", "silkworm mulberry"],
    "Crosne": ["stachys affinis", "crosne", "chinese artichoke", "japanese artichoke"],
    "Red clover": ["trifolium pratense", "trifoi rosu", "red clover herb", "meadow clover"],
    "Partridge berry": ["mitchella repens", "patrunjel salbatic", "twinberry", "squaw vine"],
    "Mikan": ["citrus unshiu", "mikan", "satsuma", "unshu orange"],
    "Jalapeno pepper": ["capsicum annuum 'jalapeño'", "jalapeno", "jalapeño", "hot pepper"],
    "Eddoe": ["colocasia antiquorum", "eddoe", "old cocoyam", "taro"],
    "Plantain": ["musa x paradisiaca", "banana de gatit", "plantain banana", "cooking plantain"],
    "Clementine": ["citrus x clementina", "clementina", "clementines", "mandarin"],
    "Black plum": ["syzygium cumini", "pruna neagra", "jambolan plum", "java plum"],
    "Green cabbage": ["brassica oleracea var. sabauda l.", "varza verde", "green headed cabbage"],
    "Green lentil": ["lens culinaris", "linte verde", "french green lentil", "puy lentil"],
    "Acorn squash": ["cucurbita pepo var. turbinata", "dovleac acorn", "acorn squash gourd"],
    "Japanese sea bass": ["lateolabrax japonicus", "biban de mare japonez", "japanese sea bass fish"],
    "Water spinach": ["ipomoea aquatica", "spanac de apa", "kangkong", "morning glory spinach"],
    "Wampee": ["clausena lansium", "wampee", "wampee fruit"],
    "Pitaya": ["hylocereus undatus", "pitaya", "dragon fruit", "pitahaya"],
    "Monk fruit": ["siraitia grosvenorii", "fructul calugarului", "luo han guo", "monkfruit"],
    "Cantaloupe melon": ["cucumis melo var. cantalupensis", "pepene cantaloupe", "cantaloupe", "rockmelon"],
    "Hawthorn": ["crataegus", "paducel", "hawthorn berries", "haws"],
    "Lantern fruit": ["physalis alkekengi", "lanterna chineza", "chinese lantern", "bladder cherry"],
    "Cape gooseberry": ["physalis peruviana", "physalis", "cape gooseberry", "goldenberry"],
}
